joint_state_topic: /right/gripper/joint_states
#closing_state_topic: /right/gripper/closing_state
position_command_topic: /right/gripper/gripper_position_controller/commands
status_command_topic: /right/gripper/gripper_status_controller/commands

max_value: 0.08
min_value: 0.0
use_binary_status_control: true
