max_value: 0.08
min_value: 0.0
joint_state_topic: gripper/joint_states
position_command_topic: gripper/gripper_position_controller/commands
status_command_topic: gripper/gripper_status_controller/commands
open_close_state_topic: gripper/open_close_state
use_binary_status_control: true