joint_state_topic: /right/gripper/joint_states
open_close_state_topic: /right/gripper/open_close_states

position_command_topic: /right/gripper/gripper_position_commands
status_command_topic: /right/gripper/gripper_status_commands

max_value: 0.08
min_value: 0.0

namespace: right

use_binary_status_control: true
